version: '3.9'

services:
  go-app:
    container_name: go-app-serverarium
    image: james_bond/go-app-serverarium
    build: .
    environment:
        DATABASE_URL: "host=go_db user=postgres password=postgres dbname =postgres sslmode=disable"
    ports:
      - "5199:5199"
      - "5399:5299"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}